src/__init__.py
import os

from flask import Flask, session


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'db.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello, World!'

    from . import db
    db.init_app(app)

    from . import auth, routes
    app.register_blueprint(auth.bp)
    app.register_blueprint(routes.bp)

    @app.context_processor
    def inject_user():
        if session:
            return dict(current_user=session['username'])
        return dict(current_user=None)

    return app

src/auth.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from src.db import get_db

bp = Blueprint('auth', __name__)


@bp.route('/signup', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']

        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (username, email, password) VALUES (?, ?, ?)",
                    (username, email, generate_password_hash(password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('auth/signup.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        # using email instead of username
        #username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        
        db = get_db()
        error = None
        # user = db.execute(
        #     'SELECT * FROM user WHERE username = ?', (username,)
        # ).fetchone()
        user = db.execute(
            'SELECT * FROM user WHERE email = ?', (email,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            session['username'] = user['username']
            return redirect(url_for('main.index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

src/routes.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from markdown import markdown

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/courses/<coursecode>/<topic>')
def course(coursecode, topic):
    html = markdown(open(f'courses/{coursecode}/{topic}.md').read())
    return render_template('course.html', course=html)

@bp.route('/courses/')
def courses():
    return render_template('courses.html')

@bp.route('/explore')
def explore():
    return render_template('explore.html')

@bp.route('/explore/specific')
def explore_specific():
    return render_template('explore-specific.html')

src/templates/course.html
<!-- Include Html Boilerplate -->
<!-- Include Nav -->

<head></head>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/markdown.css') }}">
</head>
<body>
    
</body>
</html>

{% include 'nav.html' with context %}

<!-- Body --> 
<body>
    <div class="flex justify-center min-h-screen">

        <aside class="flex-grow w-min hidden lg:block p-8 border-r-2">

            <h1>Contents</h1>
            <span>Progress 1/24</span>

            <!-- Checkboxes here -->
            
            <div class="checkbox"></div>

        </aside>
        <main class="w-full max-w-screen-lg p-8">
            <div class="markdown">
                {{ course|safe }}
            </div>
            <footer>
                <hr>
                <div class="flex justify-end">
                    <div>
                        <a href="" class="text-lg font-semibold hover:underline">Next</a>
                        <!-- Add Right Arrow Icon -->

                    </div>
                </div>

                    
                
            </footer>
        </main>
        <aside class="flex-grow w-min hidden lg:block p-8 border-l-2">
        
        </aside>

    </div>


</body>

src/templates/courses.html
{% extends 'main.html' %}
{% set active_item = 'courses' %}

{% block body %}
<main class="mx-[70px]">
  <div class="lg:grid lg:grid-cols-[1fr_204px] lg:gap-x-[78px]">
    <div class="flex justify-center mt-[13px] mb-[17px] lg:order-last">
      <div class="stats w-[204px]">
        <div id="finished" class="text-[25px]">
          Courses Finished
        </div>
        <p id="no-finished" class="text-[25px]">
          🔥 0
        </p>
        <p class="text-[22px]">
          Going strong! 💪
        </p>
      </div>
    </div>

    <div id="your-courses" class="mb-[17px]">
      <h2 class="text-[22px] mb-[12px]">
        Your Courses
      </h2>

      <!-- This should be automated -->
      <div class="item-course ">
        <div class="grid grid-cols-[128px_1fr] gap-x-[26px] my-[12px]">
          <div>
            <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
              <img src="{{ url_for('static', filename='media/icon-file.svg') }}" alt="file icon" >
            </div>
            <button class="text-[15px] bg-[#1A1A1A] text-[#FDFDFD] w-[128px] rounded-[16px] h-[30px] mt-[12px] font-bold hover:bg-[#171717] hover:text-[#EDEDED]">
              Resume
            </button>
          </div>
          <div class="course-title">
            <h3 class="line-clamp-4 text-[18px]">Linux File System</h3>
            <p class="text-[15px] line-clamp-4 h-[91px] mb-[32px] hidden lg:block">
              This course will teach you about the file structure in linux. Learning the linux file system would enable you to troubleshoot problems that you might encounter. Furthermore, it will help you know the ins and outs of your operating system.
            </p>
          </div>
        </div>
        <p class="text-[15px] line-clamp-4 mb-[32px] lg:hidden">
          This course will teach you about the file structure in linux. Learning the linux file system would enable you to troubleshoot problems that you might encounter. Furthermore, it will help you know the ins and outs of your operating system.
        </p>
      </div>
      
      <!-- This should be automated -->
      <div class="item-course ">
        <div class="grid grid-cols-[128px_1fr] gap-x-[26px] my-[12px]">
          <div>
            <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
              <h2 class="font-bold text-[#FFFFFF] text-[32px] truncate">FOSS</h2>
            </div>
            <button class="text-[15px] bg-[#1A1A1A] text-[#FDFDFD] w-[128px] rounded-[16px] h-[30px] mt-[12px] font-bold hover:bg-[#171717] hover:text-[#EDEDED]">
              Resume
            </button>
          </div>
          <div class="course-title">
            <h3 class="line-clamp-4 text-[18px]">Free and Open-Source Software</h3>
            <p class="text-[15px] line-clamp-4 h-[91px] mb-[32px] hidden lg:block">
              Free and open-source software pertains to applications with their codebase out in the public. Developers and hobbyist could contribute to the development of these applications. In addition, since the codebase is publicly available, people could raise issues in their repository when they see problematic code.
            </p>
          </div>
        </div>
        <p class="text-[15px] line-clamp-4 mb-[32px] lg:hidden">
          Free and open-source software pertains to applications with their codebase out in the public. Developers and hobbyist could contribute to the development of these applications. In addition, since the codebase is publicly available, people could raise issues in their repository when they see problematic code.
        </p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

src/templates/explore-specific.html
{% extends 'main.html' %}
{% set active_item = 'courses' %}

{% block body %}
<main class="mx-[70px]">
  <div class="lg:grid lg:grid-cols-[1fr_345px]">
    <h2 class="text-[25px] order-last flex justify-center mb-[17px]">Keep on Learning! 💡</h2>
    <div class="item-course flex gap-[24px] grid grid-cols-[128px_1fr] mb-[22px]">
      <div>
        <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
          <img src="{{ url_for('static', filename='media/icon-file.svg') }}" alt="file icon" >
        </div>
        <button class="bg-[#1A1A1A] w-full rounded-[16px] text-[#FDFDFD] font-bold py-[4px] mt-[12px]">Enroll</button>
      </div>
      <div>
        <h3 class=" line-clamp-4 text-[18px]">Linux File System</h3>
        <p class="mb-[22px] hidden lg:block mt-[4px]">This course will teach you about the file structure in linux. Learning the linux file system would enable you to troubleshoot problems that you might encounter. Furthermore, it will help you know the ins and outs of your operating system.</p>
      </div>
    </div>
  </div>
  <p class="mb-[22px] lg:hidden">This course will teach you about the file structure in linux. Learning the linux file system would enable you to troubleshoot problems that you might encounter. Furthermore, it will help you know the ins and outs of your operating system.</p>

  <div id="suggested-courses" class="mb-[17px]">
    <h2 class="text-[22px] mb-[12px]">
      Suggested
    </h2>
    <div class="flex gap-x-[64px] overflow-auto">
      <div class="item-course">
        <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
          <img src="{{ url_for('static', filename='media/icon-customize.svg') }}" alt="file icon" >
        </div>
        <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Customizing Appearance</h3>
      </div>
      <div class="item-course">
        <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
          <img src="{{ url_for('static', filename='media/icon-install.svg') }}" alt="file icon" >
        </div>
        <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Installing Fedora</h3>
      </div>
      <div class="item-course">
        <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
          <h2 class="font-bold text-[#FFFFFF] text-[32px] truncate">FOSS</h2>
        </div>
        <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Free and Open-Source Software</h3>
      </div>
    </div>
  </div>
</main>
{% endblock %}

src/templates/explore.html
{% extends 'main.html' %}
{% set active_item = 'explore' %}

{% block body %}

<main class="mx-[70px]">
  <div class="searching w-full h-[48px] mb-[16px] flex items-center bg-[#535353] rounded-[32px]">
    <input type="text" class="w-full focus:outline-none h-full bg-[#535353] ml-[20px] placeholder:text-[#D5D5D5] text-[#D5D5D5]" placeholder="Search">
    <button class="h-[24px] w-[24px] flex justify-center items-center mr-[20px]">
      <img src="{{ url_for('static', filename='/media/icon-search.svg') }}" alt="search icon">
    </button>
  </div>
  
  <div class="flex flex-row items-center mb-[24px] hover:cursor-pointer" id="filter">
    <div class="mr-[8px]">
      <img src="{{ url_for('static', filename='/media/icon-filter.svg') }}" alt="filter icon">
    </div>
    <span class="text-[15px]">Filter</span>
  </div>

  <div class="mb-[24px] hidden" id="filterOptions">
    <h2 class="text-[22px]">Difficulty</h2>
    <div class="flex items-center">
      <input type="checkbox" name="Beginner" id="beginner" class="mr-[13px]">
      <label for="beginner" class="text-[15px]">Beginner</label>
    </div>
    <div class="flex items-center">
      <input type="checkbox" name="Intermediate" id="intermediate" class="mr-[13px]">
      <label for="intermediate" class="text-[15px]">Intermediate</label>
    </div>
    <div class="flex items-center">
      <input type="checkbox" name="Advanced" id="advanced" class="mr-[13px]">
      <label for="advanced" class="text-[15px]">Advanced</label>
    </div>
    <button class="bg-[#1A1A1A] text-[#FDFDFD] px-2 py-1 rounded-lg text-[15px] font-bold">
      Apply Filter
    </button>
    <button class="border border-[#1A1A1A] px-2 py-1 rounded-lg text-[15px] font-bold">
      Reset Filter
    </button>
  </div>

  <div class="md:grid md:grid-cols-2 lg:grid lg:grid-cols-3">
    <!-- This should be automated -->
    <div class="item-course flex flex-row gap-x-[24px] mb-[24px]">
      <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
        <img src="{{ url_for('static', filename='media/icon-install.svg') }}" alt="file icon" >
      </div>
      <h3 class="w-[128px] line-clamp-4 text-[18px]">Installing Fedora</h3>
    </div>

    <!-- This should be automated -->
    <div class="item-course flex flex-row gap-x-[24px] mb-[24px]">
      <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
        <img src="{{ url_for('static', filename='media/icon-customize.svg') }}" alt="file icon" >
      </div>
      <h3 class="w-[128px] line-clamp-4 text-[18px]">Customizing Appearance</h3>
    </div>

    <!-- This should be automated -->
    <div class="item-course flex flex-row gap-x-[24px] mb-[24px]">
      <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
        <img src="{{ url_for('static', filename='media/icon-file.svg') }}" alt="file icon" >
      </div>
      <h3 class="w-[128px] line-clamp-4 text-[18px]">Linux File System</h3>
    </div>

    <!-- This should be automated -->
    <div class="item-course flex flex-row gap-x-[24px] mb-[24px]">
      <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
        <h2 class="font-bold text-[#FFFFFF] text-[32px] truncate">FOSS</h2>
      </div>
      <h3 class="w-[128px] line-clamp-4 text-[18px]">Free and Open-Source Software</h3>
    </div>

  </div>
  
</main>

{% endblock %}

src/templates/index.html
{% extends 'main.html' %}
{% set active_item = 'home' %}

{% block body %}
  <main class="mx-[70px]">
    <h1 class="hello mt-[2px] text-[22px] font-bold">
      Hi, John! 👋 
    </h1>

    <div class="lg:grid lg:grid-cols-2">
      <!-- This should be automated -->
      <div class="flex justify-center mt-[13px] mb-[17px] lg:order-last">
        <div class="stats w-[204px]">
          <div id="finished" class="text-[25px]">
            Courses Finished
          </div>
          <p id="no-finished" class="text-[25px]">
            🔥 0
          </p>
          <p class="text-[22px]">
            Going strong! 💪
          </p>
        </div>
      </div>

      <div>
        <h2 class="text-[22px] mb-[12px]">
          Linux Tuesday
        </h2>
        <!-- TODO: This should be automated -->
        <div id="linux-tues" class="mb-[17px]">
          <p class="mb-[12px]">cd is a command used to view the content of a directory. To use cd, type cd, followed by the directory name. For example: cd Downloads/.</p>
          <div class="terminal bg-[#2C2D2D] rounded-[16px]">
            <div class="window-frame h-[30px] flex justify-end items-center">
              <div class="window-frame-buttons flex justify-between w-[72px] mr-[7px]">
                <div class="w-[16px] h-[16px] rounded-[50px] bg-[#FCC82D]"></div>
                <div class="w-[16px] h-[16px] rounded-[50px] bg-[#28D33F]"></div>
                <div class="w-[16px] h-[16px] rounded-[50px] bg-[#FE6254]"></div>
              </div>
            </div>
            <div class="content px-[24px] flex justify-center flex-col pb-[30px]">
              <p class="text-[#E8E8E8] break-all">fedora@fedora:~$ cd Downloads/</p>
              <p class="text-[#E8E8E8] break-all">fedora@fedora:~/Downloads$ </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="your-courses" class="mb-[17px]">
      <h2 class="text-[22px] mb-[12px]">
        Your Courses
      </h2>

      <div class="flex gap-x-[64px] overflow-auto">
        <div class="item-course">
          <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
            <img src="{{ url_for('static', filename='media/icon-file.svg') }}" alt="file icon" >
          </div>
          <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Linux File System</h3>
        </div>
        <div class="item-course">
          <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
            <h2 class="font-bold text-[#FFFFFF] text-[32px] truncate">FOSS</h2>
          </div>
          <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Free and Open-Source Software</h3>
        </div>
      </div>
    </div>

    <div id="suggested-courses" class="mb-[17px]">
      <h2 class="text-[22px] mb-[12px]">
        Explore
      </h2>

      <div class="flex gap-x-[64px] overflow-auto">
        <div class="item-course">
          <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
            <img src="{{ url_for('static', filename='media/icon-install.svg') }}" alt="file icon" >
          </div>
          <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Installing Fedora</h3>
        </div>
        <div class="item-course">
          <div class="bg-[#535353] rounded-[16px] w-[128px] h-[96px] flex justify-center items-center">
            <img src="{{ url_for('static', filename='media/icon-customize.svg') }}" alt="file icon" >
          </div>
          <h3 class="w-[128px] h-[54px] line-clamp-2 text-[18px]">Customizing Appearance</h3>
        </div>
      </div>
    </div>

    
  </main>
{% endblock %}

src/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>append</title>
</head>

<body>

  {% set active_item = active_item|default('home') %}

  {% include 'nav.html' %}

  {% block body %}

  {% endblock %}

</body>

</html>

src/templates/nav.html
<nav class="sticky top-0 bg-[#FCFCFC] shadow-md mb-[22px]">
  <div class="flex justify-between mx-[27px] py-[19px]">
    <img src="{{ url_for('static', filename='media/icon-hamburger.svg') }}" alt="menu icon"
      class="lg:hidden cursor-pointer" id="menuButton">

    <div
      class="sidebar transform ease-in-out delay-150 fixed top-0 left-0 hidden lg:hidden bg-[#2C2D2D] h-screen w-[325px] text-[#E8E8E8]">
      <div class="flex flex-col mt-[32px]">
        <div class="flex justify-end mx-[24px] mb-[24px] cursor-pointer" id="closeMenu">
          <img src="{{ url_for('static', filename='media/icon-close.svg') }}" width="24" height="24" alt="close button">
        </div>
        <div class="flex items-center flex-col">
          <a href="{{ url_for('main.index') }}"
            class="{% if active_item == 'home'    %} active font-bold {% endif %} text-[20px] rounded-[16px] mb-[12px] p-3 hover:bg-white hover:text-gray-600 transition ease-in duration-300">Home</a>
          <a href="{{ url_for('main.courses') }}"
            class="{% if active_item == 'courses' %} active font-bold {% endif %} text-[20px] rounded-[16px] mb-[12px] p-3 hover:bg-white hover:text-gray-600 transition ease-in duration-300">Courses</a>
          <a href="{{ url_for('main.explore') }}"
            class="{% if active_item == 'explore' %} active font-bold {% endif %} text-[20px] rounded-[16px] p-3 hover:bg-white hover:text-gray-600 transition ease-in duration-300">Explore</a>
        </div>
      </div>
    </div>

    <div class="brand text-[32px]">
      >>
    </div>

    <div class="options hidden lg:block lg:grid lg:grid-cols-3 lg:gap-x-[32px]">
      <!-- active = border-b-4 border-[#535353] font-bold -->
      <a href="{{ url_for('main.index') }}"
        class="{% if active_item == 'home'    %} border-b-4 border-[#535353] font-bold {% endif %} text-[22px] text-center pt-2 px-8 hover:bg-[#535353] hover:text-white rounded-t-[16px] rounded-b-[4px] transition ease-in duration-300">Home</a>
      <a href="{{ url_for('main.courses') }}"
        class="{% if active_item == 'courses' %} border-b-4 border-[#535353] font-bold {% endif %} text-[22px] text-center pt-2 px-8 hover:bg-[#535353] hover:text-white rounded-t-[16px] rounded-b-[4px] transition ease-in duration-300">Courses</a>
      <a href="{{ url_for('main.explore') }}"
        class="{% if active_item == 'explore' %} border-b-4 border-[#535353] font-bold {% endif %} text-[22px] text-center pt-2 px-8 hover:bg-[#535353] hover:text-white rounded-t-[16px] rounded-b-[4px] transition ease-in duration-300">Explore</a>
    </div>

    <button class="flex justify-center items-center w-[51px] h-[51px] rounded-[50px] bg-[#535353] cursor-pointer z-50"
      id="userIcon">
      <img src="{{ url_for('static', filename='media/icon-user.svg') }}" height="24" width="24" alt="user icon">
    </button>
    <div class="hidden absolute right-[27px] top-[89px] bg-[#2C2D2D] py-3 px-3 rounded-lg w-[150px]" id="userOptions">
      {% if current_user == None %}
      <p class="font-bold text-[#E8E8E8] mb-2">Hi, <span class="underline">Guest</span></p>
      <hr>
      <div class="text-[#E8E8E8] my-2">User Profile</div>
      <a href="{{ url_for('auth.login') }}" class="text-[#E8E8E8] my-2">Login</a>
      {% else %}
      <p class="font-bold text-[#E8E8E8] mb-2">Hi, <span class="underline">{{current_user}}</span></p>
      <hr>
      <div class="text-[#E8E8E8] my-2">User Profile</div>
      <a href="{{ url_for('auth.logout') }}" class="text-[#E8E8E8] my-2">Logout</a>
      {% endif %}

    </div>
  </div>
</nav>

<script src="{{ url_for('static', filename='scripts/main.js') }}"></script>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>append</title>
</head>
<body>
  <div class="lg:grid lg:grid-cols-2 lg:h-screen">
    <div class="lg:bg-[#535353] lg:flex lg:justify-center lg:flex-col">
      <h1 class="text-[90px] text-center pt-[37px] text-[#535353] lg:text-[#F9F9F9]">>></h1>
      <h1 class="text-center text-[60px] -mt-10 mb-[90px] text-[#535353] lg:text-[#F9F9F9]">append</h1>
    </div>
    <form action="" class="mx-[73px] lg:flex lg:justify-center lg:flex-col">
      <h1 class="text-[30px]">Sign Up</h1>
      <h2 class="text-[25px] mb-[25px]">Join us!</h2>
      <div class="pb-[12px]">
        <label for="">Name</label> 
      </div>
      <input type="text" class="border rounded-[16px] border-black mb-[12px] w-full h-[38px] px-4">
      <div class="pb-[12px]">
        <label for="">Email</label> 
      </div>
      <input type="email" class="border rounded-[16px] border-black mb-[12px] w-full h-[38px] px-4">
      <div class="pb-[12px]">
        <label for="">Password</label>
      </div>
      <input type="password" class="border rounded-[16px] border-black mb-[25px] w-full h-[38px] px-4">
      <button type="submit" class="font-bold border bg-[#535353] w-full rounded-[16px] mb-[25px] text-[22px] py-[9px] text-[#F9F9F9]">Login</button>
      <p>Already have an account? <a href="/login" class="text-blue-700 font-bold">Login</a></p>
    </form>
  </div>
  
</body>
</html>